"""执行平台与评测台共用的节点契约；导入目录不加载节点、配置或外部服务。"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from types import MappingProxyType
from typing import Literal


@dataclass(frozen=True, slots=True)
class NodeSpec:
    name: str
    product: str
    callable_path: str
    input_fields: tuple[str, ...]
    output_fields: tuple[str, ...] = ()
    side_effect: Literal["none", "read", "write"] = "none"
    surfaces: tuple[Literal["execution", "evaluation"], ...] = ("execution", "evaluation")


_NODES = (
    NodeSpec(
        name="ingest",
        product="main",
        callable_path="app.nodes.ingest:ingest",
        input_fields=("room_id", "trace_id"),
        output_fields=(
            "reply_text",
            "api_result",
            "api_code",
            "error",
            "expected_action",
            "tickers",
            "place_params",
            "cancel_params",
            "confirm",
            "query_filter",
            "close_params",
            "ticker_hitl_candidates",
            "swap_counterparty_picks",
            "swap_ticker_picks",
        ),
    ),
    NodeSpec(
        name="entry_route",
        product="main",
        callable_path="app.nodes.entry_route:entry_route",
        input_fields=("fast_query", "existing_command", "at_bot"),
        surfaces=("execution",),
    ),
    NodeSpec(
        name="quick_inquiry",
        product="main",
        callable_path="app.nodes.fast_query:quick_inquiry",
        input_fields=(
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "guid",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("api_code", "api_result", "reply_text"),
        side_effect="write",
    ),
    NodeSpec(
        name="existing_command_query",
        product="main",
        callable_path="app.nodes.fast_query:existing_command_query",
        input_fields=("raw_text", "room_id", "operator_user_id", "user_id"),
        output_fields=("api_code", "api_result", "reply_text"),
        side_effect="read",
    ),
    NodeSpec(
        name="pre_route",
        product="main",
        callable_path="app.nodes.pre_route:pre_route",
        input_fields=("option_counterparties_raw", "swap_counterparties_raw", "quote_content"),
        output_fields=("option_counterparties", "swap_counterparties", "quote_ticker_candidates"),
    ),
    NodeSpec(
        name="intent_route",
        product="main",
        callable_path="app.nodes.intent_route:intent_route",
        input_fields=("raw_text", "quote_content", "input_files", "product_type"),
        output_fields=("product_type", "swap_input_mode"),
        side_effect="read",
    ),
    NodeSpec(
        name="swap",
        product="main",
        callable_path="app.subgraphs.swap.graph:build_swap_graph",
        input_fields=(
            "swap_input_mode",
            "error",
            "intent",
            "input_files",
            "place_params",
            "tickers",
            "swap_counterparty_picks",
            "swap_ticker_picks",
            "quote_ticker_candidates",
            "last_confirmed_params",
            "swap_counterparties",
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        side_effect="write",
        surfaces=("execution",),
    ),
    NodeSpec(
        name="option",
        product="main",
        callable_path="app.subgraphs.option.graph:build_option_graph",
        input_fields=(
            "error",
            "intent",
            "history_messages",
            "bot_name",
            "option_counterparties",
            "last_confirmed_params",
            "tickers",
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        side_effect="write",
        surfaces=("execution",),
    ),
    NodeSpec(
        name="option_close",
        product="main",
        callable_path="app.subgraphs.close.graph:build_close_graph",
        input_fields=(
            "error",
            "intent",
            "history_messages",
            "option_counterparties",
            "last_confirmed_params",
            "conversation_orders",
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        side_effect="write",
        surfaces=("execution",),
    ),
    NodeSpec(
        name="fallback",
        product="main",
        callable_path="app.nodes.fallback:fallback",
        input_fields=("error",),
    ),
    NodeSpec(
        name="persist_intent",
        product="main",
        callable_path="app.nodes.persist_intent:make_persist_intent",
        input_fields=("conversation_id", "message_id", "intent", "product_type"),
        side_effect="write",
    ),
    NodeSpec(
        name="persist",
        product="main",
        callable_path="app.nodes.persist:persist",
        input_fields=(
            "trace",
            "message_id",
            "conversation_id",
            "trace_id",
            "product_type",
            "intent",
        ),
        side_effect="write",
    ),
    NodeSpec(
        name="render",
        product="main",
        callable_path="app.nodes.render:render",
        input_fields=(
            "reply_text",
            "product_type",
            "api_result",
            "error",
            "ticker_hitl_candidates",
            "tickers",
            "place_params",
            "raw_text",
            "intent",
            "quote_content",
            "close_params",
            "cancel_params",
            "confirm",
            "expected_action",
            "api_code",
        ),
        output_fields=("reply_text",),
    ),
    NodeSpec(
        name="remember_confirmed_params",
        product="main",
        callable_path="app.nodes.remember_confirmed:remember_confirmed_params",
        input_fields=(
            "product_type",
            "expected_action",
            "error",
            "api_code",
            "intent",
            "message_id",
            "place_params",
            "confirm",
            "cancel_params",
            "close_params",
            "api_result",
        ),
        output_fields=("last_confirmed_params",),
    ),
    NodeSpec(
        name="record_history",
        product="main",
        callable_path="app.nodes.record_history:record_history",
        input_fields=("raw_text", "reply_text"),
        output_fields=("history_messages",),
    ),
    NodeSpec(
        name="option_intent",
        product="option",
        callable_path="app.subgraphs.option.intent:option_intent",
        input_fields=(
            "raw_text",
            "quote_content",
            "history_messages",
            "bot_name",
            "option_counterparties",
        ),
        output_fields=("intent",),
    ),
    NodeSpec(
        name="option_extract_inquiry",
        product="option",
        callable_path="app.subgraphs.option.extract_inquiry:build_inquiry_graph",
        input_fields=(
            "error",
            "history_messages",
            "tickers",
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("expected_action", "place_params", "api_code", "api_result", "reply_text"),
        side_effect="write",
    ),
    NodeSpec(
        name="option_extract_place",
        product="option",
        callable_path="app.subgraphs.option.extract_place:option_extract_place",
        input_fields=(
            "history_messages",
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("expected_action", "place_params", "api_code", "api_result", "reply_text"),
        side_effect="write",
    ),
    NodeSpec(
        name="option_extract_confirm_place",
        product="option",
        callable_path="app.subgraphs.option.extract_confirm_place:option_extract_confirm_place",
        input_fields=(
            "history_messages",
            "last_confirmed_params",
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("expected_action", "confirm", "api_code", "api_result", "reply_text"),
        side_effect="write",
    ),
    NodeSpec(
        name="option_extract_cancel_place",
        product="option",
        callable_path="app.subgraphs.option.extract_cancel_place:option_extract_cancel_place",
        input_fields=(
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("expected_action", "cancel_params", "api_code", "api_result", "reply_text"),
        side_effect="write",
    ),
    NodeSpec(
        name="option_extract_cancel",
        product="option",
        callable_path="app.subgraphs.option.extract_cancel:option_extract_cancel",
        input_fields=(
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("expected_action", "cancel_params", "api_code", "api_result", "reply_text"),
        side_effect="write",
    ),
    NodeSpec(
        name="option_extract_confirm_cancel",
        product="option",
        callable_path="app.subgraphs.option.extract_confirm_cancel:option_extract_confirm_cancel",
        input_fields=(
            "last_confirmed_params",
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("expected_action", "confirm", "api_code", "api_result", "reply_text"),
        side_effect="write",
    ),
    NodeSpec(
        name="option_extract_query",
        product="option",
        callable_path="app.subgraphs.option.extract_query:option_extract_query",
        input_fields=(
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("query_filter", "api_code", "api_result", "reply_text"),
        side_effect="read",
    ),
    NodeSpec(
        name="option_unknown",
        product="option",
        callable_path="app.subgraphs.option.graph:option_unknown",
        input_fields=("intent",),
    ),
    NodeSpec(
        name="inquiry_fast_parse",
        product="option",
        callable_path="app.subgraphs.option.extract_inquiry:inquiry_fast_parse",
        input_fields=("raw_text",),
        output_fields=("iq_rfq_data",),
        side_effect="read",
    ),
    NodeSpec(
        name="inquiry_fast_submit",
        product="option",
        callable_path="app.subgraphs.option.extract_inquiry:inquiry_fast_submit",
        input_fields=(
            "iq_rfq_data",
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("api_code", "api_result", "reply_text"),
        side_effect="write",
    ),
    NodeSpec(
        name="inquiry_extract",
        product="option",
        callable_path="app.subgraphs.option.extract_inquiry:inquiry_extract",
        input_fields=("raw_text", "quote_content", "history_messages"),
        output_fields=("iq_raw_params", "iq_field_records"),
        side_effect="read",
    ),
    NodeSpec(
        name="inquiry_normalize",
        product="option",
        callable_path="app.subgraphs.option.extract_inquiry:inquiry_normalize",
        input_fields=("iq_raw_params", "iq_field_records"),
        output_fields=("iq_order_list", "iq_types", "field_records"),
    ),
    NodeSpec(
        name="inquiry_submit",
        product="option",
        callable_path="app.subgraphs.option.extract_inquiry:inquiry_submit",
        input_fields=(
            "iq_order_list",
            "iq_types",
            "iq_raw_params",
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("expected_action", "place_params", "api_code", "api_result", "reply_text"),
        side_effect="write",
    ),
    NodeSpec(
        name="swap_intent",
        product="swap",
        callable_path="app.subgraphs.swap.intent:swap_intent",
        input_fields=("raw_text", "quote_content", "swap_counterparties", "conversation_id"),
        output_fields=("intent",),
    ),
    NodeSpec(
        name="swap_place_order",
        product="swap",
        callable_path="app.subgraphs.swap.place_order:swap_place_order",
        input_fields=("raw_text", "quote_content", "swap_counterparties", "conversation_id"),
        output_fields=("expected_action", "place_params", "tickers", "ticker_hitl_candidates"),
        side_effect="read",
    ),
    NodeSpec(
        name="swap_recognize_fresh_counterparty",
        product="swap",
        callable_path="app.subgraphs.swap.fresh_counterparty:swap_recognize_fresh_counterparty",
        input_fields=("raw_text", "swap_counterparties", "place_params"),
        output_fields=("place_params",),
        side_effect="read",
    ),
    NodeSpec(
        name="swap_select_counterparty",
        product="swap",
        callable_path="app.subgraphs.swap.select_counterparty:swap_select_counterparty",
        input_fields=("raw_text", "swap_counterparties", "quote_content"),
        output_fields=("swap_counterparty_picks",),
        side_effect="read",
    ),
    NodeSpec(
        name="swap_select_ticker",
        product="swap",
        callable_path="app.subgraphs.swap.select_ticker:swap_select_ticker",
        input_fields=("raw_text", "quote_content", "quote_ticker_candidates"),
        output_fields=("swap_ticker_picks",),
        side_effect="read",
    ),
    NodeSpec(
        name="swap_apply_picks",
        product="swap",
        callable_path="app.subgraphs.swap.apply_picks:swap_apply_picks",
        input_fields=(
            "place_params",
            "swap_counterparty_picks",
            "swap_counterparties",
            "swap_ticker_picks",
            "quote_ticker_candidates",
        ),
        output_fields=("place_params",),
    ),
    NodeSpec(
        name="swap_place_order_submit",
        product="swap",
        callable_path="app.subgraphs.swap.place_order:swap_place_order_submit",
        input_fields=(
            "place_params",
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("place_params", "api_code", "api_result", "reply_text"),
        side_effect="write",
    ),
    NodeSpec(
        name="swap_confirm",
        product="swap",
        callable_path="app.subgraphs.swap.confirm:swap_confirm",
        input_fields=(
            "intent",
            "last_confirmed_params",
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("expected_action", "confirm", "api_code", "api_result", "reply_text"),
        side_effect="write",
    ),
    NodeSpec(
        name="swap_cancel",
        product="swap",
        callable_path="app.subgraphs.swap.cancel:swap_cancel",
        input_fields=(
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("expected_action", "cancel_params", "api_code", "api_result", "reply_text"),
        side_effect="write",
    ),
    NodeSpec(
        name="swap_query_order",
        product="swap",
        callable_path="app.subgraphs.swap.query_order:swap_query_order",
        input_fields=(
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("query_filter", "api_code", "api_result", "reply_text"),
        side_effect="read",
    ),
    NodeSpec(
        name="swap_unknown",
        product="swap",
        callable_path="app.subgraphs.swap.graph:swap_unknown",
        input_fields=("intent",),
    ),
    NodeSpec(
        name="swap_image_order",
        product="swap",
        callable_path="app.subgraphs.swap.multimodal:swap_image_order",
        input_fields=("input_files", "conversation_id", "swap_counterparties", "raw_text"),
        output_fields=("expected_action", "place_params", "tickers"),
        side_effect="read",
    ),
    NodeSpec(
        name="swap_excel_order",
        product="swap",
        callable_path="app.subgraphs.swap.multimodal:swap_excel_order",
        input_fields=("input_files", "conversation_id", "raw_text", "swap_counterparties"),
        output_fields=("expected_action", "place_params", "tickers"),
        side_effect="read",
    ),
    NodeSpec(
        name="close_intent",
        product="option_close",
        callable_path="app.subgraphs.close.intent:close_intent",
        input_fields=("raw_text", "quote_content", "history_messages"),
        output_fields=("intent",),
        side_effect="read",
    ),
    NodeSpec(
        name="close_holding_query",
        product="option_close",
        callable_path="app.subgraphs.close.holding_query:close_holding_query",
        input_fields=(
            "option_counterparties",
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("close_params", "api_code", "api_result", "reply_text"),
        side_effect="read",
    ),
    NodeSpec(
        name="close_place_close",
        product="option_close",
        callable_path="app.subgraphs.close.place_close:build_place_close_graph",
        input_fields=(
            "error",
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("expected_action", "close_params", "api_code", "api_result", "reply_text"),
        side_effect="write",
    ),
    NodeSpec(
        name="close_confirm_close",
        product="option_close",
        callable_path="app.subgraphs.close.confirm_close:close_confirm_close",
        input_fields=(
            "last_confirmed_params",
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("expected_action", "confirm", "api_code", "api_result", "reply_text"),
        side_effect="write",
    ),
    NodeSpec(
        name="close_cancel_close",
        product="option_close",
        callable_path="app.subgraphs.close.cancel_close:close_cancel_close",
        input_fields=(
            "conversation_orders",
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("expected_action", "cancel_params", "api_code", "api_result", "reply_text"),
        side_effect="write",
    ),
    NodeSpec(
        name="close_confirm_cancel",
        product="option_close",
        callable_path="app.subgraphs.close.confirm_cancel:close_confirm_cancel",
        input_fields=(
            "last_confirmed_params",
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("expected_action", "confirm", "api_code", "api_result", "reply_text"),
        side_effect="write",
    ),
    NodeSpec(
        name="close_query_status",
        product="option_close",
        callable_path="app.subgraphs.close.query_status:close_query_status",
        input_fields=(
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("query_filter", "api_code", "api_result", "reply_text"),
        side_effect="read",
    ),
    NodeSpec(
        name="close_unknown",
        product="option_close",
        callable_path="app.subgraphs.close.graph:close_unknown",
        input_fields=("intent",),
    ),
    NodeSpec(
        name="place_close_parse",
        product="option_close",
        callable_path="app.subgraphs.close.place_close:place_close_parse",
        input_fields=("raw_text", "quote_content"),
        output_fields=("pc_parsed",),
    ),
    NodeSpec(
        name="place_close_fetch_orders",
        product="option_close",
        callable_path="app.subgraphs.close.place_close:place_close_fetch_orders",
        input_fields=("pc_parsed", "room_id", "message_id"),
        output_fields=("pc_order_data",),
        side_effect="read",
    ),
    NodeSpec(
        name="place_close_extract",
        product="option_close",
        callable_path="app.subgraphs.close.place_close:place_close_extract",
        input_fields=("raw_text", "quote_content", "pc_parsed", "pc_order_data"),
        output_fields=("pc_candidates", "pc_llm_output"),
        side_effect="read",
    ),
    NodeSpec(
        name="place_close_normalize",
        product="option_close",
        callable_path="app.subgraphs.close.place_close:place_close_normalize",
        input_fields=("pc_parsed", "pc_candidates", "raw_text", "quote_content", "pc_order_data"),
        output_fields=("pc_close_orders", "pc_reject_reply", "pc_reject_decision", "field_records"),
    ),
    NodeSpec(
        name="place_close_validate",
        product="option_close",
        callable_path="app.subgraphs.close.place_close:place_close_validate",
        input_fields=("pc_close_orders",),
        output_fields=("pc_reject_reply", "pc_reject_decision"),
    ),
    NodeSpec(
        name="place_close_submit",
        product="option_close",
        callable_path="app.subgraphs.close.place_close:place_close_submit",
        input_fields=(
            "pc_close_orders",
            "pc_llm_output",
            "guid",
            "operator_user_id",
            "raw_text",
            "quote_content",
            "quote_appinfo",
            "conversation_id",
            "room_id",
            "user_id",
            "message_id",
        ),
        output_fields=("expected_action", "close_params", "api_code", "api_result", "reply_text"),
        side_effect="write",
    ),
    NodeSpec(
        name="place_close_reject",
        product="option_close",
        callable_path="app.subgraphs.close.place_close:place_close_reject",
        input_fields=("pc_close_orders", "pc_reject_reply", "pc_reject_decision", "pc_llm_output"),
        output_fields=("expected_action", "close_params", "reply_text", "intent"),
    ),
    NodeSpec(
        name="swap_extract_candidates",
        product="swap",
        callable_path="app.subgraphs.swap.place_order:swap_extract_candidates",
        input_fields=("raw_text", "quote_content", "history_messages", "swap_counterparties"),
        output_fields=("sp_candidates", "sp_prompt_name"),
        side_effect="read",
        surfaces=("evaluation",),
    ),
    NodeSpec(
        name="swap_normalize",
        product="swap",
        callable_path="app.subgraphs.swap.place_order:swap_normalize",
        input_fields=("raw_text", "quote_content", "history_messages", "sp_candidates"),
        output_fields=("sp_params", "field_records", "place_params", "reply_text"),
        surfaces=("evaluation",),
    ),
    NodeSpec(
        name="swap_place_result",
        product="swap",
        callable_path="app.subgraphs.swap.place_order:swap_place_result",
        input_fields=("sp_params", "sp_prompt_name"),
        output_fields=("expected_action", "place_params"),
        surfaces=("evaluation",),
    ),
)

NODE_CATALOG: Mapping[str, NodeSpec] = MappingProxyType({node.name: node for node in _NODES})
if len(NODE_CATALOG) != len(_NODES):
    raise ValueError("Duplicate node identity in catalogue")
