"""自动化工作台可展示节点的稳定注册表。"""

from __future__ import annotations

from harness.node_annotations import NodeDefinition

_BACKEND_OUTPUTS = ("api_code", "api_result", "reply_text")
_PLACE_OUTPUTS = ("expected_action", "place_params", *_BACKEND_OUTPUTS)
_CONFIRM_OUTPUTS = ("expected_action", "confirm", *_BACKEND_OUTPUTS)
_CANCEL_OUTPUTS = ("expected_action", "cancel_params", *_BACKEND_OUTPUTS)
_INQUIRY_OUTPUTS = (
    "expected_action",
    "place_params",
    *_BACKEND_OUTPUTS,
)
_TRACE_ONLY_REASON = "仅输出动态 trace 或空对象，无稳定业务输出"
_INGEST_OUTPUTS = (
    "reply_text",
    "api_result",
    "api_code",
    "error",
    "expected_action",
    "tickers",
    "place_params",
    "cancel_params",
    "confirm",
    "query_filter",
    "close_params",
    "ticker_hitl_candidates",
    "swap_counterparty_picks",
    "swap_ticker_picks",
)


def _node(
    name: str,
    product_type: str,
    category: str,
    *,
    replayable: bool,
    side_effect: str = "none",
    annotatable: bool = True,
    annotation_reason: str = "",
    inputs: tuple[str, ...] = (),
    outputs: tuple[str, ...] = (),
    callable_path: str = "",
) -> NodeDefinition:
    return NodeDefinition(
        name=name,
        product_type=product_type,
        category=category,
        replayable=replayable,
        side_effect=side_effect,
        annotatable=annotatable,
        annotation_reason=annotation_reason,
        input_fields=inputs,
        output_fields=outputs,
        callable_path=callable_path,
    )


_NODES = (
    # 主图公共节点
    _node(
        "ingest",
        "common",
        "输入处理",
        replayable=True,
        inputs=("room_id", "trace_id"),
        outputs=_INGEST_OUTPUTS,
        callable_path="app.nodes.ingest:ingest",
    ),
    _node(
        "pre_route",
        "common",
        "一级路由",
        replayable=True,
        inputs=("option_counterparties_raw", "swap_counterparties_raw", "quote_content"),
        outputs=(
            "option_counterparties",
            "swap_counterparties",
            "quote_ticker_candidates",
        ),
        callable_path="app.nodes.pre_route:pre_route",
    ),
    _node(
        "intent_route",
        "common",
        "一级路由",
        replayable=True,
        side_effect="read",
        inputs=("raw_text", "quote_content", "input_files", "product_type"),
        outputs=("product_type", "swap_input_mode"),
        callable_path="app.nodes.intent_route:intent_route",
    ),
    _node(
        "quick_inquiry",
        "common",
        "快速询价",
        replayable=False,
        side_effect="write",
        outputs=_BACKEND_OUTPUTS,
    ),
    _node(
        "existing_command_query",
        "common",
        "存量指令",
        replayable=True,
        side_effect="read",
        inputs=("raw_text", "room_id", "operator_user_id", "user_id"),
        outputs=("api_code", "api_result", "reply_text"),
        callable_path="app.nodes.fast_query:existing_command_query",
    ),
    _node(
        "plan_instructions",
        "common",
        "多指令规划",
        replayable=True,
        side_effect="read",
        inputs=("raw_text", "quote_content", "input_files"),
        outputs=("sub_instructions",),
        callable_path="app.graph.instructions:plan_instructions",
    ),
    _node(
        "instructions",
        "common",
        "多指令执行",
        replayable=False,
        side_effect="write",
        outputs=("instruction_results", "reply_text", "error", "product_type", "intent"),
    ),
    _node(
        "fallback",
        "common",
        "输出处理",
        replayable=False,
        annotatable=False,
        annotation_reason=_TRACE_ONLY_REASON,
    ),
    _node(
        "render",
        "common",
        "输出处理",
        replayable=True,
        inputs=(
            "raw_text",
            "product_type",
            "intent",
            "reply_text",
            "api_result",
            "error",
            "ticker_hitl_candidates",
            "tickers",
            "place_params",
            "close_params",
            "cancel_params",
            "confirm",
            "quote_content",
        ),
        outputs=("reply_text",),
        callable_path="app.nodes.render:render",
    ),
    _node(
        "remember_confirmed_params",
        "common",
        "会话记忆",
        replayable=True,
        inputs=(
            "product_type",
            "intent",
            "expected_action",
            "error",
            "api_code",
            "place_params",
            "confirm",
            "cancel_params",
            "close_params",
            "api_result",
            "message_id",
        ),
        outputs=("last_confirmed_params",),
        callable_path=("app.nodes.remember_confirmed:remember_confirmed_params"),
    ),
    _node(
        "record_history",
        "common",
        "会话记忆",
        replayable=True,
        inputs=("raw_text", "reply_text"),
        outputs=("history_messages",),
        callable_path="app.nodes.record_history:record_history",
    ),
    _node(
        "persist_intent",
        "common",
        "持久化",
        replayable=False,
        side_effect="write",
        annotatable=False,
        annotation_reason=_TRACE_ONLY_REASON,
    ),
    _node(
        "persist",
        "common",
        "持久化",
        replayable=False,
        side_effect="write",
        annotatable=False,
        annotation_reason=_TRACE_ONLY_REASON,
    ),
    # 互换
    _node(
        "swap_intent",
        "swap",
        "意图识别",
        replayable=True,
        inputs=("raw_text", "quote_content", "swap_counterparties", "conversation_id"),
        outputs=("intent",),
        callable_path="app.subgraphs.swap.intent:swap_intent",
    ),
    _node(
        "swap_place_order",
        "swap",
        "参数提取",
        replayable=True,
        side_effect="read",
        inputs=("raw_text", "quote_content", "swap_counterparties", "conversation_id"),
        outputs=("expected_action", "place_params", "tickers", "ticker_hitl_candidates"),
        callable_path="app.subgraphs.swap.place_order:swap_place_order",
    ),
    _node(
        "swap_extract_candidates",
        "swap",
        "参数候选提取",
        replayable=True,
        side_effect="read",
        inputs=("raw_text", "quote_content", "history_messages", "swap_counterparties"),
        outputs=("sp_candidates", "sp_prompt_name"),
        callable_path="app.subgraphs.swap.place_order:swap_extract_candidates",
    ),
    _node(
        "swap_normalize",
        "swap",
        "参数归一化",
        replayable=True,
        inputs=("raw_text", "quote_content", "history_messages", "sp_candidates"),
        outputs=("sp_params", "field_records", "place_params", "reply_text"),
        callable_path="app.subgraphs.swap.place_order:swap_normalize",
    ),
    _node(
        "swap_place_result",
        "swap",
        "参数汇总",
        replayable=True,
        inputs=("sp_params", "sp_prompt_name"),
        outputs=("expected_action", "place_params"),
        callable_path="app.subgraphs.swap.place_order:swap_place_result",
    ),
    _node(
        "swap_recognize_fresh_counterparty",
        "swap",
        "交易对手识别",
        replayable=True,
        side_effect="read",
        inputs=("raw_text", "swap_counterparties", "place_params"),
        outputs=("place_params",),
        callable_path=("app.subgraphs.swap.fresh_counterparty:swap_recognize_fresh_counterparty"),
    ),
    _node(
        "swap_select_counterparty",
        "swap",
        "交易对手选择",
        replayable=True,
        side_effect="read",
        inputs=("raw_text", "quote_content", "swap_counterparties"),
        outputs=("swap_counterparty_picks",),
        callable_path="app.subgraphs.swap.select_counterparty:swap_select_counterparty",
    ),
    _node(
        "swap_select_ticker",
        "swap",
        "标的选择",
        replayable=True,
        side_effect="read",
        inputs=("raw_text", "quote_content", "quote_ticker_candidates"),
        outputs=("swap_ticker_picks",),
        callable_path="app.subgraphs.swap.select_ticker:swap_select_ticker",
    ),
    _node(
        "swap_apply_picks",
        "swap",
        "参数合并",
        replayable=True,
        inputs=(
            "place_params",
            "swap_counterparty_picks",
            "swap_ticker_picks",
            "swap_counterparties",
            "quote_ticker_candidates",
        ),
        outputs=("place_params",),
        callable_path="app.subgraphs.swap.apply_picks:swap_apply_picks",
    ),
    _node(
        "swap_place_order_submit",
        "swap",
        "后端写入",
        replayable=False,
        side_effect="write",
        outputs=("place_params", *_BACKEND_OUTPUTS),
    ),
    _node(
        "swap_confirm",
        "swap",
        "后端写入",
        replayable=False,
        side_effect="write",
        outputs=_CONFIRM_OUTPUTS,
    ),
    _node(
        "swap_cancel",
        "swap",
        "后端写入",
        replayable=False,
        side_effect="write",
        outputs=_CANCEL_OUTPUTS,
    ),
    _node(
        "swap_query_order",
        "swap",
        "后端查询",
        replayable=True,
        side_effect="read",
        inputs=(
            "raw_text",
            "quote_content",
            "conversation_id",
            "message_id",
            "room_id",
            "user_id",
        ),
        outputs=("query_filter", "api_code", "api_result", "reply_text"),
        callable_path="app.subgraphs.swap.query_order:swap_query_order",
    ),
    _node(
        "swap_unknown",
        "swap",
        "兜底",
        replayable=False,
        annotatable=False,
        annotation_reason=_TRACE_ONLY_REASON,
    ),
    _node(
        "swap_image_order",
        "swap",
        "多模态",
        replayable=False,
        side_effect="read",
        annotatable=True,
        annotation_reason="外部文件 URL 存在网络访问风险，仅保留标注",
        inputs=("raw_text", "input_files", "swap_counterparties"),
        outputs=("expected_action", "place_params", "tickers"),
    ),
    _node(
        "swap_excel_order",
        "swap",
        "多模态",
        replayable=False,
        side_effect="read",
        annotatable=True,
        annotation_reason="外部文件 URL 存在网络访问风险，仅保留标注",
        inputs=("raw_text", "input_files", "swap_counterparties"),
        outputs=("expected_action", "place_params", "tickers"),
    ),
    # 期权开仓
    _node(
        "option_intent",
        "option",
        "意图识别",
        replayable=True,
        inputs=("raw_text", "quote_content", "history_messages"),
        outputs=("intent",),
        callable_path="app.subgraphs.option.intent:option_intent",
    ),
    _node(
        "option_extract_inquiry",
        "option",
        "询价子图",
        replayable=False,
        side_effect="write",
        outputs=_INQUIRY_OUTPUTS,
    ),
    _node(
        "inquiry_fast_parse",
        "option",
        "快速询价解析",
        replayable=True,
        side_effect="read",
        inputs=("raw_text",),
        outputs=("iq_rfq_data",),
        callable_path="app.subgraphs.option.extract_inquiry:inquiry_fast_parse",
    ),
    _node(
        "inquiry_fast_submit",
        "option",
        "后端写入",
        replayable=False,
        side_effect="write",
        outputs=_BACKEND_OUTPUTS,
    ),
    _node(
        "inquiry_extract",
        "option",
        "参数提取",
        replayable=True,
        side_effect="read",
        inputs=("raw_text",),
        outputs=("iq_raw_params", "iq_field_records"),
        callable_path="app.subgraphs.option.extract_inquiry:inquiry_extract",
    ),
    _node(
        "inquiry_normalize",
        "option",
        "参数归一化",
        replayable=True,
        inputs=("iq_raw_params", "iq_field_records"),
        outputs=("iq_order_list", "iq_types", "field_records"),
        callable_path="app.subgraphs.option.extract_inquiry:inquiry_normalize",
    ),
    _node(
        "inquiry_submit",
        "option",
        "后端写入",
        replayable=False,
        side_effect="write",
        outputs=_INQUIRY_OUTPUTS,
    ),
    _node(
        "option_extract_place",
        "option",
        "后端写入",
        replayable=False,
        side_effect="write",
        outputs=_PLACE_OUTPUTS,
    ),
    _node(
        "option_extract_confirm_place",
        "option",
        "后端写入",
        replayable=False,
        side_effect="write",
        outputs=_CONFIRM_OUTPUTS,
    ),
    _node(
        "option_extract_cancel_place",
        "option",
        "后端写入",
        replayable=False,
        side_effect="write",
        outputs=_CANCEL_OUTPUTS,
    ),
    _node(
        "option_extract_cancel",
        "option",
        "后端写入",
        replayable=False,
        side_effect="write",
        outputs=_CANCEL_OUTPUTS,
    ),
    _node(
        "option_extract_confirm_cancel",
        "option",
        "后端写入",
        replayable=False,
        side_effect="write",
        outputs=_CONFIRM_OUTPUTS,
    ),
    _node(
        "option_extract_query",
        "option",
        "后端查询",
        replayable=True,
        side_effect="read",
        inputs=(
            "raw_text",
            "quote_content",
            "conversation_id",
            "message_id",
            "room_id",
            "user_id",
        ),
        outputs=("query_filter", "api_code", "api_result", "reply_text"),
        callable_path="app.subgraphs.option.extract_query:option_extract_query",
    ),
    _node(
        "option_unknown",
        "option",
        "兜底",
        replayable=False,
        annotatable=False,
        annotation_reason=_TRACE_ONLY_REASON,
    ),
    # 期权平仓
    _node(
        "close_intent",
        "option_close",
        "意图识别",
        replayable=True,
        side_effect="read",
        inputs=("raw_text", "quote_content", "history_messages"),
        outputs=("intent",),
        callable_path="app.subgraphs.close.intent:close_intent",
    ),
    _node(
        "close_holding_query",
        "option_close",
        "后端查询",
        replayable=True,
        side_effect="read",
        inputs=(
            "raw_text",
            "option_counterparties",
            "conversation_id",
            "message_id",
            "room_id",
            "user_id",
        ),
        outputs=("close_params", "api_code", "api_result", "reply_text"),
        callable_path="app.subgraphs.close.holding_query:close_holding_query",
    ),
    _node(
        "close_place_close",
        "option_close",
        "平仓申请子图",
        replayable=False,
        side_effect="write",
        outputs=("expected_action", "close_params", "api_code", "api_result", "reply_text"),
    ),
    _node(
        "close_confirm_close",
        "option_close",
        "后端写入",
        replayable=False,
        side_effect="write",
        outputs=("expected_action", "confirm", "api_code", "api_result", "reply_text"),
    ),
    _node(
        "close_cancel_close",
        "option_close",
        "后端写入",
        replayable=False,
        side_effect="write",
        outputs=("expected_action", "cancel_params", "api_code", "api_result", "reply_text"),
    ),
    _node(
        "close_confirm_cancel",
        "option_close",
        "后端写入",
        replayable=False,
        side_effect="write",
        outputs=("expected_action", "confirm", "api_code", "api_result", "reply_text"),
    ),
    _node(
        "close_query_status",
        "option_close",
        "后端查询",
        replayable=True,
        side_effect="read",
        inputs=(
            "raw_text",
            "conversation_id",
            "message_id",
            "room_id",
            "user_id",
        ),
        outputs=("query_filter", "api_code", "api_result", "reply_text"),
        callable_path="app.subgraphs.close.query_status:close_query_status",
    ),
    _node(
        "close_unknown",
        "option_close",
        "兜底",
        replayable=False,
        annotatable=False,
        annotation_reason=_TRACE_ONLY_REASON,
    ),
    _node(
        "place_close_parse",
        "option_close",
        "引用解析",
        replayable=True,
        inputs=("raw_text", "quote_content"),
        outputs=("pc_parsed",),
        callable_path="app.subgraphs.close.place_close:place_close_parse",
    ),
    _node(
        "place_close_fetch_orders",
        "option_close",
        "后端查询",
        replayable=True,
        side_effect="read",
        inputs=("pc_parsed", "room_id", "message_id"),
        outputs=("pc_order_data",),
        callable_path="app.subgraphs.close.place_close:place_close_fetch_orders",
    ),
    _node(
        "place_close_extract",
        "option_close",
        "参数提取",
        replayable=True,
        side_effect="read",
        inputs=("raw_text", "quote_content", "pc_parsed", "pc_order_data"),
        outputs=("pc_candidates", "pc_llm_output"),
        callable_path="app.subgraphs.close.place_close:place_close_extract",
    ),
    _node(
        "place_close_normalize",
        "option_close",
        "参数归一化",
        replayable=True,
        inputs=(
            "raw_text",
            "quote_content",
            "pc_parsed",
            "pc_order_data",
            "pc_candidates",
        ),
        outputs=("pc_close_orders", "pc_reject_reply", "pc_reject_decision", "field_records"),
        callable_path="app.subgraphs.close.place_close:place_close_normalize",
    ),
    _node(
        "place_close_validate",
        "option_close",
        "参数校验",
        replayable=True,
        inputs=("pc_close_orders",),
        outputs=("pc_reject_reply", "pc_reject_decision"),
        callable_path="app.subgraphs.close.place_close:place_close_validate",
    ),
    _node(
        "place_close_submit",
        "option_close",
        "后端写入",
        replayable=False,
        side_effect="write",
        outputs=("expected_action", "close_params", "api_code", "api_result", "reply_text"),
    ),
    _node(
        "place_close_reject",
        "option_close",
        "请求拒绝",
        replayable=True,
        inputs=("pc_close_orders", "pc_reject_reply", "pc_reject_decision", "pc_llm_output"),
        outputs=("expected_action", "close_params", "reply_text", "intent"),
        callable_path="app.subgraphs.close.place_close:place_close_reject",
    ),
)

DEFAULT_NODE_REGISTRY: dict[str, NodeDefinition] = {node.name: node for node in _NODES}


__all__ = ["DEFAULT_NODE_REGISTRY"]
